# Force deploy: 0

name: Run tests and deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/on-push.yml'
      - 'fbase/*.rules'
      - 'fbase/*.json'
      - 'fbase/functions/**'

jobs:
  run_firebase_tests:
    name: Tests
    uses: webhookbuddy/webhookbuddy/.github/workflows/run-firebase-tests.yml@dev
    secrets:
      firebaseToken: ${{secrets.FIREBASE_TOKEN}}
  # Job to run change detection: https://github.com/dorny/paths-filter#examples
  changes_dev:
    needs: run_firebase_tests
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/dev'}}
    name: Changes dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Set job outputs to values from filter step
    outputs:
      firebase: ${{steps.filter.outputs.firebase}}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: 'dev'
          filters: |
            firebase:
              - '**/on-push.yml'
              - 'fbase/*.rules'
              - 'fbase/*.json'
              - 'fbase/functions/**'
  changes_main:
    needs: run_firebase_tests
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    name: Changes main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Set job outputs to values from filter step
    outputs:
      firebase: ${{steps.filter.outputs.firebase}}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            firebase:
              - '**/on-push.yml'
              - 'fbase/*.rules'
              - 'fbase/*.json'
              - 'fbase/functions/**'
  deploy_firebase_dev:
    needs: changes_dev
    if: ${{needs.changes_dev.outputs.firebase == 'true'}}
    name: DEV
    uses: webhookbuddy/webhookbuddy/.github/workflows/deploy-firebase.yml@dev
    with:
      projectAlias: dev
    secrets:
      firebaseToken: ${{secrets.FIREBASE_TOKEN}}
  deploy_firebase_prod:
    needs: changes_main
    if: ${{needs.changes_main.outputs.firebase == 'true'}}
    name: PROD
    uses: webhookbuddy/webhookbuddy/.github/workflows/deploy-firebase.yml@dev
    with:
      projectAlias: prod
    secrets:
      firebaseToken: ${{secrets.FIREBASE_TOKEN}}
